"""wyrd-bo01.2: convert the bundled ``{culture}_place_names.json`` gazetteer
into an L2 JSONL toponym source, so the proportions corpus lives in the one
JSONL→DB→bundle pipeline like every other source (rando-port playbook).

The gazetteer JSON is a 3-level ``{country: {region: [names]}}`` dict, which
maps 1:1 onto the ``toponym`` table's ``(modern_name, country, region)``. The
emitted JSONL carries one ``source`` row (``{culture}_place_names`` — a
low-trust seed source, the place-name analogue of ``rando-port``) plus one
``toponym`` row per place. No decompositions: the gazetteer supplies *names*;
attested sources (KEPN / scholarly) supply the breakdowns, and the Phase-3
readiness dashboard tracks how much of the gazetteer those attested sources
have covered (gating the gazetteer's retirement).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TextIO

# Cultures with a bundled gazetteer. Order is the canonical emit order.
CULTURES: tuple[str, ...] = ("english", "scottish", "welsh", "irish", "breton")


def source_id_for(culture: str) -> str:
    """The seed source_id for a culture's gazetteer (e.g. ``english_place_names``)."""
    return f"{culture}_place_names"


def _source_row(culture: str) -> dict[str, str]:
    return {
        "_type": "source",
        "ref": source_id_for(culture),
        "title": (
            f"{culture.title()} place-name gazetteer (settlements by county) — "
            "low-trust proportions seed corpus"
        ),
        "notes": (
            "Generated by `wyrd kenning lexicon convert-place-names` from the "
            "bundled gazetteer JSON (wyrd-bo01.2). Names only — attested "
            "decompositions come from KEPN / scholarly sources."
        ),
    }


def emit_place_names_jsonl(culture: str, data: dict, sink: TextIO) -> int:
    """Write the gazetteer ``data`` (``{country: {region: [names]}}``) as L2
    JSONL to ``sink``: one source row + one toponym row per distinct
    ``(name, country, region)``. Returns the toponym-row count.

    ``ref`` encodes all three natural-key fields so distinct places that
    share a ``modern_name`` (e.g. *California* in two counties) get distinct
    refs; the build's ``_insert_toponym`` then merges any that collide with an
    already-present toponym onto the existing row (wyrd-bo01.1).
    """
    sink.write(json.dumps(_source_row(culture), ensure_ascii=False) + "\n")
    n = 0
    seen: set[tuple[str, str, str]] = set()
    for country, regions in data.items():
        for region, names in regions.items():
            for name in names:
                key = (str(name), str(country), str(region))
                if key in seen:
                    continue
                seen.add(key)
                row = {
                    "_type": "toponym",
                    "ref": f"{name}@{country}/{region}",
                    "modern_name": str(name),
                    "country": str(country),
                    "region": str(region),
                }
                sink.write(json.dumps(row, ensure_ascii=False) + "\n")
                n += 1
    return n


def convert_file(culture: str, json_path: Path, jsonl_path: Path) -> int:
    """Read the bundled gazetteer JSON for ``culture`` and write its L2 JSONL.
    Returns the toponym count. Truncates/rewrites ``jsonl_path``."""
    data = json.loads(json_path.read_text(encoding="utf-8"))
    jsonl_path.parent.mkdir(parents=True, exist_ok=True)
    with jsonl_path.open("w", encoding="utf-8") as sink:
        return emit_place_names_jsonl(culture, data, sink)
