"""wyrd-c6o1.5: operator allowlist for which name STRUCTURES the generator may
use, sourced from the bundled ``data/structures.yaml``.

A *structure* is a ``struct_key`` (see ``word_to_key`` / ``NameGenerator.structs``):
a tuple of words, each a tuple of morpheme keys ``(location, [name], [saint],
[single])``. Some corpus-derived structures make poor names (e.g. a lone
dictionary word, ``(bare)``), so the operator curates a YAML allowlist:

    "(bare)": {enabled: false}     # lone dictionary word — Old, Green, Bath
    "(pre+post)": {enabled: true}  # Place- -shire (one word, two morphemes)

Each entry defaults to ``enabled: true``; the operator opts a structure OUT by
setting ``enabled: false``. A structure ABSENT from the file is enabled — so a
bundle rebuild that surfaces a brand-new structure is generated by default
(operator opts out, never in). This is the SINGLE operator-facing structure
filter (wyrd-c6o1.5 migrated the old ``_is_single_morpheme_structure`` /
"``<Bare>``" special-case here); ``is_structurally_grammatical`` (wyrd-zzli) stays
a separate hard grammaticality gate.

Loaded like ``register_effects.yaml`` (a package-data YAML shipped in the bundle
via the ``data/*.yaml`` glob), lazily + cached.
"""

from __future__ import annotations

from functools import lru_cache
from importlib import resources
from types import MappingProxyType

import yaml

_DATA_PACKAGE = "wyrd.generators.kenning.data"
_FILENAME = "structures.yaml"


class StructureAllowlistError(ValueError):
    """Malformed ``structures.yaml`` (bad root shape or duplicate label)."""


class _NoDuplicateKeysLoader(yaml.SafeLoader):
    """SafeLoader that rejects duplicate top-level labels (a duplicate would
    silently shadow the operator's earlier curation)."""


def _no_duplicate_mapping(loader: yaml.Loader, node: yaml.nodes.MappingNode) -> dict:
    mapping: dict = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=True)
        if key in mapping:
            raise StructureAllowlistError(
                f"duplicate structure label {key!r} at line {key_node.start_mark.line + 1}"
            )
        mapping[key] = loader.construct_object(value_node, deep=True)
    return mapping


_NoDuplicateKeysLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _no_duplicate_mapping
)


def _morpheme_label(key: tuple) -> str:
    """One morpheme key → label: its location plus any name/saint flag. The
    ``single`` flag is dropped — ``word_to_key`` adds it to (and only to)
    one-morpheme words, so it's fully implied by the word's shape and carries no
    extra identity (dropping it keeps the label injective)."""
    location = key[0]
    flags = [f for f in key[1:] if f != "single"]
    return f"{location}[{','.join(flags)}]" if flags else location


def struct_key_to_label(struct_key: tuple) -> str:
    """Canonical human-readable label for a ``struct_key`` — the YAML lookup key.

    Words are space-separated; morphemes within a word are joined with ``+`` and
    wrapped in parens. Examples::

        ((("bare","single"),),)                 -> "(bare)"
        ((("bare","name","single"),),)          -> "(bare[name])"
        ((("pre",),("post",)),)                 -> "(pre+post)"
        ((("bare","single"),),(("bare","single"),)) -> "(bare) (bare)"
    """
    return " ".join("(" + "+".join(_morpheme_label(k) for k in word) + ")" for word in struct_key)


def load_structure_allowlist_from_text(text: str) -> dict[str, bool]:
    """Parse a ``structures.yaml`` string into ``{label: enabled}``. An entry's
    value is a mapping whose ``enabled`` key (default ``True``) drives the flag;
    a bare/empty entry means enabled. Raises on a non-mapping root or a
    non-mapping / non-bool-``enabled`` entry."""
    parsed = yaml.load(text, Loader=_NoDuplicateKeysLoader)
    if parsed is None:
        return {}
    if not isinstance(parsed, dict):
        raise StructureAllowlistError(
            f"structures.yaml root must be a mapping, got {type(parsed).__name__}"
        )
    out: dict[str, bool] = {}
    for label, entry in parsed.items():
        if not isinstance(label, str):
            # A non-string label (YAML `123:` → int, `true:` → bool) can never
            # match a struct_key_to_label string, so it'd be a silently-dead entry
            # — reject it loudly instead.
            raise StructureAllowlistError(
                f"structure label must be a string, got {type(label).__name__}: {label!r}"
            )
        if entry is None:
            out[label] = True
            continue
        if not isinstance(entry, dict):
            raise StructureAllowlistError(
                f"structure {label!r}: entry must be a mapping, got {type(entry).__name__}"
            )
        enabled = entry.get("enabled", True)
        if not isinstance(enabled, bool):
            raise StructureAllowlistError(
                f"structure {label!r}: 'enabled' must be a bool, got {type(enabled).__name__}"
            )
        out[label] = enabled
    return out


@lru_cache(maxsize=1)
def _load_bundled_cached() -> MappingProxyType:
    """Read + parse the bundled ``structures.yaml`` once per process. A missing
    file → empty allowlist (everything enabled) so a bundle without the file
    degrades to no-filtering, not a crash.

    Returned as a read-only ``MappingProxyType`` — this is shared, long-lived
    cached state, so a caller must not be able to mutate it (wyrd-i7uy discipline)."""
    try:
        text = resources.files(_DATA_PACKAGE).joinpath(_FILENAME).read_text(encoding="utf-8")
    except FileNotFoundError:
        return MappingProxyType({})
    return MappingProxyType(load_structure_allowlist_from_text(text))


def is_structure_enabled(struct_key: tuple) -> bool:
    """Whether the operator allowlist permits ``struct_key``. Absent label →
    enabled (rebuild-surfaced structures default on)."""
    return _load_bundled_cached().get(struct_key_to_label(struct_key), True)
