"""wyrd-c6o1.5: operator allowlist for which name STRUCTURES the generator may
use, sourced from the bundled ``data/structures.yaml``.

A *structure* is a ``struct_key`` (see ``word_to_key`` / ``NameGenerator.structs``):
a tuple of words, each a tuple of morpheme keys ``(location, [name], [saint],
[single])``. Some corpus-derived structures make poor names (e.g. a lone
dictionary word, ``(bare)``), so the operator curates a YAML allowlist.

wyrd-hzqs: the file is **per-language** — a mapping of CULTURE → section, where
each section is the ``{label: {enabled}}`` map for that culture (frequencies of a
structure differ per language, and English run-on trash isn't Irish's). The
``# <weight> (<pct>%)`` comment on each row is advisory (the loader ignores it) —
it's a dump-time snapshot to help the operator curate by commonness::

    english:
      "(bare)": {enabled: false}     # 4402 (16.60%)  lone dictionary word
      "(pre+post)": {enabled: true}  # 6958 (26.24%)  Place- -shire
    scottish:
      "(pre+post)": {enabled: true}  # 412 (44.6%)

Each entry defaults to ``enabled: true``; the operator opts a structure OUT by
setting ``enabled: false``. A structure ABSENT from its culture section is
enabled, and an ABSENT culture section is fully enabled — so a bundle rebuild that
surfaces a brand-new structure is generated by default (operator opts out, never
in). This is the SINGLE operator-facing structure filter (wyrd-c6o1.5 migrated
the old ``_is_single_morpheme_structure`` / "``<Bare>``" special-case here);
``is_structurally_grammatical`` (wyrd-zzli) stays a separate hard grammaticality
gate.

Loaded like ``register_effects.yaml`` (a package-data YAML shipped in the bundle
via the ``data/*.yaml`` glob), lazily + cached.
"""

from __future__ import annotations

from functools import lru_cache
from importlib import resources
from types import MappingProxyType

import yaml

_DATA_PACKAGE = "wyrd.generators.kenning.data"
_FILENAME = "structures.yaml"


class StructureAllowlistError(ValueError):
    """Malformed ``structures.yaml`` (bad root shape or duplicate label)."""


class _NoDuplicateKeysLoader(yaml.SafeLoader):
    """SafeLoader that rejects duplicate top-level labels (a duplicate would
    silently shadow the operator's earlier curation)."""


def _no_duplicate_mapping(loader: yaml.Loader, node: yaml.nodes.MappingNode) -> dict:
    mapping: dict = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=True)
        if key in mapping:
            raise StructureAllowlistError(
                f"duplicate structure label {key!r} at line {key_node.start_mark.line + 1}"
            )
        mapping[key] = loader.construct_object(value_node, deep=True)
    return mapping


_NoDuplicateKeysLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, _no_duplicate_mapping
)


def _morpheme_label(key: tuple) -> str:
    """One morpheme key → label: its location plus any name/saint flag. The
    ``single`` flag is dropped — ``word_to_key`` adds it to (and only to)
    one-morpheme words, so it's fully implied by the word's shape and carries no
    extra identity (dropping it keeps the label injective)."""
    location = key[0]
    flags = [f for f in key[1:] if f != "single"]
    return f"{location}[{','.join(flags)}]" if flags else location


def struct_key_to_label(struct_key: tuple) -> str:
    """Canonical human-readable label for a ``struct_key`` — the YAML lookup key.

    Words are space-separated; morphemes within a word are joined with ``+`` and
    wrapped in parens. Examples::

        ((("bare","single"),),)                 -> "(bare)"
        ((("bare","name","single"),),)          -> "(bare[name])"
        ((("pre",),("post",)),)                 -> "(pre+post)"
        ((("bare","single"),),(("bare","single"),)) -> "(bare) (bare)"
    """
    return " ".join("(" + "+".join(_morpheme_label(k) for k in word) + ")" for word in struct_key)


def load_structure_allowlist_from_text(text: str) -> dict[str, dict[str, bool]]:
    """Parse a sectioned ``structures.yaml`` into ``{culture: {label: enabled}}``.

    The file is a mapping of CULTURE → section; each section is a mapping of
    structure label → entry. An entry is a mapping whose ``enabled`` key
    (default ``True``) drives the flag; a bare/empty entry — or an empty section
    — means enabled. Raises on a non-mapping root/section/entry, a non-string
    culture/label, or a non-bool ``enabled``.

    wyrd-hzqs: pre-hzqs this was a single flat ``{label: enabled}`` map; the
    format is now per-culture, so an old flat file fails loudly here (its
    ``{enabled: bool}`` values aren't section mappings) — re-dump to migrate."""
    parsed = yaml.load(text, Loader=_NoDuplicateKeysLoader)
    if parsed is None:
        return {}
    if not isinstance(parsed, dict):
        raise StructureAllowlistError(
            f"structures.yaml root must be a mapping of culture sections, "
            f"got {type(parsed).__name__}"
        )
    out: dict[str, dict[str, bool]] = {}
    for culture, section in parsed.items():
        if not isinstance(culture, str):
            raise StructureAllowlistError(
                f"culture section name must be a string, got {type(culture).__name__}: {culture!r}"
            )
        if section is None:
            out[culture] = {}
            continue
        if not isinstance(section, dict):
            raise StructureAllowlistError(
                f"culture section {culture!r} must be a mapping, got {type(section).__name__}"
            )
        out[culture] = _parse_section(culture, section)
    return out


def _parse_section(culture: str, section: dict) -> dict[str, bool]:
    """Parse one culture's ``{label: {enabled}}`` section into ``{label: bool}``."""
    out: dict[str, bool] = {}
    for label, entry in section.items():
        if not isinstance(label, str):
            # A non-string label (YAML `123:` → int, `true:` → bool) can never
            # match a struct_key_to_label string, so it'd be a silently-dead entry
            # — reject it loudly instead.
            raise StructureAllowlistError(
                f"{culture}: structure label must be a string, got "
                f"{type(label).__name__}: {label!r}"
            )
        if entry is None:
            out[label] = True
            continue
        if not isinstance(entry, dict):
            raise StructureAllowlistError(
                f"{culture}/{label!r}: entry must be a mapping, got {type(entry).__name__}"
            )
        enabled = entry.get("enabled", True)
        if not isinstance(enabled, bool):
            raise StructureAllowlistError(
                f"{culture}/{label!r}: 'enabled' must be a bool, got {type(enabled).__name__}"
            )
        out[label] = enabled
    return out


@lru_cache(maxsize=1)
def _load_bundled_cached() -> MappingProxyType:
    """Read + parse the bundled ``structures.yaml`` once per process. A missing
    file → empty allowlist (everything enabled) so a bundle without the file
    degrades to no-filtering, not a crash.

    Returned as a NESTED read-only ``MappingProxyType`` (outer culture map +
    each section) — this is shared, long-lived cached state, so a caller must not
    be able to mutate it at either level (wyrd-i7uy discipline)."""
    try:
        text = resources.files(_DATA_PACKAGE).joinpath(_FILENAME).read_text(encoding="utf-8")
    except FileNotFoundError:
        return MappingProxyType({})
    parsed = load_structure_allowlist_from_text(text)
    return MappingProxyType({culture: MappingProxyType(s) for culture, s in parsed.items()})


def is_structure_enabled(struct_key: tuple, culture: str | None) -> bool:
    """Whether the operator allowlist permits ``struct_key`` for ``culture``.

    Absent label → enabled (rebuild-surfaced structures default on). An absent
    culture section, or ``culture is None`` (a legacy NameGenerator built without
    a culture), → enabled: fail-open, no section means no curation yet."""
    if culture is None:
        return True
    section = _load_bundled_cached().get(culture)
    if section is None:
        return True
    return section.get(struct_key_to_label(struct_key), True)
