"""meaning_synset + empirical priors

Revision ID: 0007_synsets_priors
Revises: 0006_toponyms
Create Date: 2026-05-18

Two unrelated-but-each-small-enough-to-share-a-migration layers:

* ``meaning_synset`` + ``etymon_meaning_synset`` — D28 semantic
  equivalence catalog ('water/flowing', 'hill/rounded'). Distinct
  from ``etymon.cognate_id`` (etymological descent).
* ``empirical_priors_native`` + ``empirical_priors_loan`` —
  wyrd-ecjp.2 / D36.4 / D36.7 vector-driven generator priors. Raw
  occurrence counts per (culture × position × tag × era × lemma).
  Re-generated by ``lexicon mine-empirical-baselines --apply``.
"""

from __future__ import annotations

from alembic import op

revision = "0007_synsets_priors"
down_revision = "0006_toponyms"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE meaning_synset (
          id              INTEGER PRIMARY KEY AUTOINCREMENT,
          canonical_label TEXT NOT NULL UNIQUE,
          hypernym_id     INTEGER REFERENCES meaning_synset(id) ON DELETE SET NULL,
          notes           TEXT
        )
        """
    )
    op.execute("CREATE INDEX idx_meaning_synset_hypernym ON meaning_synset(hypernym_id)")

    op.execute(
        """
        CREATE TABLE etymon_meaning_synset (
          etymon_id         INTEGER NOT NULL REFERENCES etymon(id) ON DELETE CASCADE,
          meaning_synset_id INTEGER NOT NULL REFERENCES meaning_synset(id) ON DELETE CASCADE,
          fit               TEXT NOT NULL CHECK (fit IN ('core', 'peripheral')),
          PRIMARY KEY (etymon_id, meaning_synset_id)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX idx_etymon_meaning_synset_synset
          ON etymon_meaning_synset(meaning_synset_id)
        """
    )

    op.execute(
        """
        CREATE TABLE empirical_priors_native (
          culture       TEXT NOT NULL,
          position      TEXT NOT NULL,
          tag           TEXT NOT NULL,
          era_midpoint  INTEGER NOT NULL,
          lemma_ref     TEXT NOT NULL,
          count         INTEGER NOT NULL CHECK (count > 0),
          PRIMARY KEY (culture, position, tag, era_midpoint, lemma_ref)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX idx_priors_native_cell
          ON empirical_priors_native(culture, position, tag, era_midpoint)
        """
    )
    op.execute("CREATE INDEX idx_priors_native_lemma ON empirical_priors_native(lemma_ref)")

    op.execute(
        """
        CREATE TABLE empirical_priors_loan (
          donor         TEXT NOT NULL,
          recipient     TEXT NOT NULL,
          position      TEXT NOT NULL,
          tag           TEXT NOT NULL,
          era_midpoint  INTEGER NOT NULL,
          lemma_ref     TEXT NOT NULL,
          count         INTEGER NOT NULL CHECK (count > 0),
          PRIMARY KEY (donor, recipient, position, tag, era_midpoint, lemma_ref)
        )
        """
    )
    op.execute(
        """
        CREATE INDEX idx_priors_loan_cell
          ON empirical_priors_loan(donor, recipient, position, tag, era_midpoint)
        """
    )
    op.execute("CREATE INDEX idx_priors_loan_lemma ON empirical_priors_loan(lemma_ref)")


def downgrade() -> None:
    op.execute("DROP TABLE empirical_priors_loan")
    op.execute("DROP TABLE empirical_priors_native")
    op.execute("DROP TABLE etymon_meaning_synset")
    op.execute("DROP TABLE meaning_synset")
