"""genitive-s split prior — wyrd-aicu.9

Per ``(long_form, short_form)`` genitive-overlap pair (``ston`` / ``ton``,
``sley`` / ``ley`` …) the raw count of scholarly toponym breakdowns whose final
element is the genitive-split reading (the short suffix ``S`` — tūn → town) vs
the literal long form (``L`` — stān → stone), classified by the breakdown's
cognate-cluster. Re-generated by ``lexicon mine-genitive-priors --apply``; raw
counts only (smoothing + backoff live at lookup time, mirroring
``empirical_priors``).

L3 derived artifact — re-derivable from ``toponym_etymology`` +
``toponym_attestation`` + ``reflex`` + the cognate clusters, so a rebuild leaves
it empty until the enrichment pass runs.
"""

from __future__ import annotations

from alembic import op

revision = "0018_genitive_split_prior"
down_revision = "0017_dedash_reflex_surface_form"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE genitive_split_prior (
          long_form        TEXT NOT NULL,
          short_form       TEXT NOT NULL,
          split_count      INTEGER NOT NULL CHECK (split_count >= 0),
          literal_count    INTEGER NOT NULL CHECK (literal_count >= 0),
          PRIMARY KEY (long_form, short_form)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE genitive_split_prior")
