"""``wyrd kenning dump-structures`` — refresh the per-language structure allowlist
(wyrd-c6o1.5 / wyrd-hzqs).

Walks every culture's mined structures in the runtime DB, labels each
(``struct_key_to_label``), and emits a PER-LANGUAGE sectioned YAML — one
``"<label>": {enabled: <bool>}  # <weight> (<pct>%)`` row per structure, grouped
under a top-level culture key (``english:``, ``scottish:``, …). The operator
commits this as ``wyrd/generators/kenning/data/structures.yaml`` and curates by
flipping unwanted structures to ``enabled: false``; the generator filters its
per-culture structure pool through that section at load time
(``runtime.structure_allowlist.is_structure_enabled``).

REFRESH-MERGE (wyrd-hzqs): a re-run is a merge, not a regen-from-scratch. The
existing committed file is read first; for every structure already present, the
operator's ``enabled`` value WINS (so each ``false`` is sticky). A structure NOT
in the old file is NEW → it gets the default (``true``, except a lone
single-morpheme ``<Bare>`` which seeds ``false``, preserving the migrated
wyrd-g1hj exclusion). A previously-disabled structure no longer in the corpus
just DROPS OUT. The dump prints a per-culture NEW/DROPPED summary to stderr so the
operator gets an explicit "go filter these" signal on top of the git diff.

Rows are sorted ALPHABETICALLY (stable) within each section so a rebuild that only
nudges frequencies doesn't reorder the file and churn the diff — new structures
show up as clean added lines. The ``# <weight> (<pct>%)`` comment is advisory
(the loader ignores it); it's a dump-time snapshot to curate by commonness.
Ungrammatical structures (wyrd-zzli) are omitted entirely — a hard gate, not
operator-curatable.

Output goes to stdout (or ``--output PATH``) — never writes the package-data file
directly, so the change stays review-friendly.
"""

from __future__ import annotations

from importlib import resources
from pathlib import Path

import click

from wyrd.generators.kenning import CULTURES
from wyrd.generators.kenning.runtime.proportions import is_structurally_grammatical, word_to_key
from wyrd.generators.kenning.runtime.runtime_db import get_runtime_db
from wyrd.generators.kenning.runtime.runtime_db_adapter import proportions_dict_for_culture
from wyrd.generators.kenning.runtime.structure_allowlist import (
    load_structure_allowlist_from_text,
    struct_key_to_label,
)

_DATA_PACKAGE = "wyrd.generators.kenning.data"
_FILENAME = "structures.yaml"

_HEADER = """\
# wyrd-c6o1.5 / wyrd-hzqs: PER-LANGUAGE structure allowlist. Top-level keys are
# cultures; each section has one entry per name structure mined from that
# culture's corpus. Each defaults to `enabled: true`; set `enabled: false` to
# forbid the generator from using that structure FOR THAT CULTURE. A structure
# absent from a section (or an absent section) is enabled.
#
# Regenerated by `wyrd kenning dump-structures` as a REFRESH-MERGE: re-running
# keeps every `enabled: false` you set and adds new structures as enabled — see
# the stderr summary + git diff for what's new since the last dump. The
# `# <weight> (<pct>%)` comment is an advisory frequency snapshot (the loader
# ignores it). Rows are alpha-sorted; do not hand-reorder.
#
# Lone-dictionary-word structures ("(bare)") seed disabled (migrated wyrd-g1hj).
"""


def _single_morpheme(struct_key: tuple) -> bool:
    """The migrated wyrd-g1hj default: a structure of one morpheme total renders
    as a flat lone dictionary word — seed it disabled.

    This lives HERE as a one-shot default-SEED for NEW labels in the dumped YAML,
    NOT as a runtime filter — the only runtime structure filter is the allowlist
    itself (``is_structure_enabled``). So there's still exactly one filtering path."""
    return sum(len(word) for word in struct_key) <= 1


def _read_merge_base(merge_from: Path | None) -> dict[str, dict[str, bool]]:
    """The existing curation to preserve: ``{culture: {label: enabled}}``. Reads
    ``merge_from`` if given (mainly for tests), else the bundled committed file.
    A missing file → empty (everything fresh-default); a malformed file raises
    loudly (don't silently wipe curation)."""
    if merge_from is not None:
        if not merge_from.exists():
            return {}
        return load_structure_allowlist_from_text(merge_from.read_text(encoding="utf-8"))
    try:
        text = resources.files(_DATA_PACKAGE).joinpath(_FILENAME).read_text(encoding="utf-8")
    except FileNotFoundError:
        return {}
    return load_structure_allowlist_from_text(text)


def _culture_weights(conn, culture: str) -> tuple[dict[str, int], dict[str, bool]]:
    """For one culture: ``{label: summed-weight}`` over grammatical structures and
    ``{label: is-single-morpheme}``. ``struct_key_to_label`` is injective, but
    weights are summed defensively in case two struct_keys ever share a label."""
    weights: dict[str, int] = {}
    single: dict[str, bool] = {}
    for element in proportions_dict_for_culture(conn, culture)["structures"]:
        words = tuple(word_to_key(w) for w in element["words"])
        if not is_structurally_grammatical(words):
            continue  # hard-gated (wyrd-zzli); not operator-curatable
        label = struct_key_to_label(words)
        weights[label] = weights.get(label, 0) + element["proportion"]
        single[label] = _single_morpheme(words)
    return weights, single


def _build(conn, merge_base: dict[str, dict[str, bool]]):
    """Returns (sections, summary):
    sections[culture] = [(label, enabled, weight, pct), …] alpha-sorted;
    summary[culture]  = (total, [(label, weight, pct) new…], [dropped labels…])."""
    sections: dict[str, list] = {}
    summary: dict[str, tuple] = {}
    for culture in CULTURES:
        weights, single = _culture_weights(conn, culture)
        total = sum(weights.values()) or 1
        base = merge_base.get(culture, {})
        rows, new_rows = [], []
        for label in sorted(weights):  # alphabetical / stable → diff-friendly
            pct = 100 * weights[label] / total
            if label in base:
                enabled = base[label]  # operator curation wins (sticky false)
            else:
                enabled = not single[label]  # new → default on, bare seeds off
                new_rows.append((label, weights[label], pct))
            rows.append((label, enabled, weights[label], pct))
        dropped = sorted(set(base) - set(weights))
        sections[culture] = rows
        summary[culture] = (len(rows), new_rows, dropped)
    return sections, summary


def _render(sections: dict[str, list]) -> str:
    out = [_HEADER]
    for culture in CULTURES:
        out.append(f"{culture}:")
        for label, enabled, weight, pct in sections.get(culture, []):
            out.append(f'  "{label}": {{enabled: {str(enabled).lower()}}}  # {weight} ({pct:.2f}%)')
        out.append("")  # blank line between sections
    return "\n".join(out).rstrip("\n") + "\n"


def _emit_summary(summary: dict[str, tuple]) -> None:
    """Per-culture progress + the NEW/DROPPED 'go filter these' signal (stderr)."""
    for culture in CULTURES:
        total, new_rows, dropped = summary[culture]
        delta = ""
        if new_rows or dropped:
            delta = f" (+{len(new_rows)} new, -{len(dropped)} dropped since last dump)"
        click.echo(f"{culture}: {total} structures{delta}", err=True)
        for label, weight, pct in new_rows:
            click.echo(f"  NEW: {label}  # {weight} ({pct:.2f}%)", err=True)
        for label in dropped:
            click.echo(f"  DROPPED: {label}", err=True)


@click.command("dump-structures")
@click.option(
    "--output",
    type=click.Path(dir_okay=False, path_type=Path),
    default=None,
    help="Write to this path instead of stdout.",
)
@click.option(
    "--merge-from",
    type=click.Path(dir_okay=False, path_type=Path),
    default=None,
    help="Preserve existing curation from this file instead of the bundled "
    "structures.yaml (mainly for tests).",
)
def dump_structures(output: Path | None, merge_from: Path | None) -> None:
    """Refresh the per-language structures.yaml allowlist (preserves curation)."""
    conn = get_runtime_db()
    merge_base = _read_merge_base(merge_from)
    sections, summary = _build(conn, merge_base)
    text = _render(sections)
    if output is not None:
        output.write_text(text, encoding="utf-8")
        click.echo(f"wrote {output}", err=True)
    else:
        click.echo(text, nl=False)
    _emit_summary(summary)


def add_to(parent: click.Group) -> None:
    """Register ``dump-structures`` on the top-level ``@cli`` group."""
    parent.add_command(dump_structures)
